version: '1.0'

services:
      
  mssql:
    container_name: taskmanager-db
    image: "mcr.microsoft.com/mssql/server"
    container_name: taskmanager-mssql
    environment:
      SA_PASSWORD: "Develop@123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
      
      
  migrations:
    container_name: taskmanager-migrations
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      - mssql
    command:
      [
        "./scripts/apply-migrations.sh"
      ]
      
      
  integration-tests:
    container_name: taskmanager-integration-tests
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      - mssql
      - migrations
    env_file:
      - .env
    command:
      [
        "./scripts/wait-for-it.sh",
        "mssql:1433",
        "-t",
        "30",
        "--",
        "./scripts/start-tests.sh"
      ]
      
      
  api:
    container_name: taskmanager-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=localhost
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/taskmanagerapp.pfx
      - WEBSITES_PORT=80
      — WEBSITES_CONTAINER_START_TIME_LIMIT=1500
    depends_on:
      - mssql
      - migrations
    entrypoint: ["dotnet", "TaskManager.Api.dll"]
    command:
      [
        "./scripts/wait-for-it.sh",
        "mssql:1433",
        "-t",
        "120",
        "--",
      ]
    ports:
      - 80:80
